// packages/solid/src/TrafficLight.tsx
import { createSignal, mergeProps, Show } from "solid-js";
import type { Component, JSX } from "solid-js";
import type { SolidIconProps } from "./createIcon.tsx";
import { CloseIcon, MaximizeIcon, MinimizeIcon } from "./icons.tsx";

type TrafficLightState = "default" | "hover" | "active";
type TrafficLightButton = "close" | "minimize" | "maximize";

export type TrafficLightProps = {
  close?: boolean;
  minimize?: boolean;
  maximize?: boolean;
  disabled?: boolean;
  size?: number;
  gap?: number;
  onClose?: () => void;
  onMinimize?: () => void;
  onMaximize?: () => void;
};

function useButtonState() {
  const [state, setState] = createSignal<TrafficLightState>("default");

  const onMouseEnter: JSX.EventHandlerUnion<HTMLButtonElement, MouseEvent> = () => {
    setState((s) => (s === "default" ? "hover" : s));
  };

  const onMouseLeave: JSX.EventHandlerUnion<HTMLButtonElement, MouseEvent> = () => {
    setState("default");
  };

  const onMouseDown: JSX.EventHandlerUnion<HTMLButtonElement, MouseEvent> = () => {
    setState("active");
  };

  const onMouseUp: JSX.EventHandlerUnion<HTMLButtonElement, MouseEvent> = () => {
    setState((s) => (s === "active" ? "hover" : s));
  };

  const onBlur: JSX.EventHandlerUnion<HTMLButtonElement, FocusEvent> = () => {
    setState("default");
  };

  return { state, onMouseEnter, onMouseLeave, onMouseDown, onMouseUp, onBlur };
}

export function TrafficLight(rawProps: TrafficLightProps) {
  const props = mergeProps(
    {
      close: true,
      minimize: true,
      maximize: true,
      disabled: false,
      size: 12,
      gap: 8,
    },
    rawProps,
  );

  const closeBtn = useButtonState();
  const minimizeBtn = useButtonState();
  const maximizeBtn = useButtonState();

  const containerStyle = (): JSX.CSSProperties => ({
    display: "flex",
    "align-items": "center",
    gap: `${props.gap}px`,
  });

  function renderButton(
    kind: TrafficLightButton,
    Icon: Component<SolidIconProps>,
    state: () => TrafficLightState,
    handlers: ReturnType<typeof useButtonState>,
  ) {
    const buttonStyle = (): JSX.CSSProperties => ({
      border: "none",
      padding: 0,
      background: "transparent",
      cursor: props.disabled ? "default" : "pointer",
      display: "inline-flex",
      "align-items": "center",
      "justify-content": "center",
      opacity: props.disabled ? 0.45 : 1,
    });

    const clickHandler =
      kind === "close" ? props.onClose : kind === "minimize" ? props.onMinimize : props.onMaximize;

    return (
      <button
        type="button"
        class={`mac-btn mac-btn--${kind}`}
        style={buttonStyle()}
        disabled={props.disabled}
        aria-disabled={props.disabled ? "true" : undefined}
        onClick={() => {
          if (!props.disabled) clickHandler?.();
        }}
        onMouseEnter={props.disabled ? undefined : handlers.onMouseEnter}
        onMouseLeave={props.disabled ? undefined : handlers.onMouseLeave}
        onMouseDown={props.disabled ? undefined : handlers.onMouseDown}
        onMouseUp={props.disabled ? undefined : handlers.onMouseUp}
        onBlur={props.disabled ? undefined : handlers.onBlur}
      >
        <Icon state={props.disabled ? "default" : state()} width={props.size} height={props.size} />
      </button>
    );
  }

  return (
    <div class="mac-traffic-light" style={containerStyle()}>
      <Show when={props.close}>{renderButton("close", CloseIcon, closeBtn.state, closeBtn)}</Show>
      <Show when={props.minimize}>
        {renderButton("minimize", MinimizeIcon, minimizeBtn.state, minimizeBtn)}
      </Show>
      <Show when={props.maximize}>
        {renderButton("maximize", MaximizeIcon, maximizeBtn.state, maximizeBtn)}
      </Show>
    </div>
  );
}

// packages/svelte/src/TrafficLight.svelte
<script lang="ts">
  import type { IconState } from "@traffic-light/svg";
  import CloseIcon from "./icons/CloseIcon.svelte";
  import MaximizeIcon from "./icons/MaximizeIcon.svelte";
  import MinimizeIcon from "./icons/MinimizeIcon.svelte";

  export let close = true;
  export let minimize = true;
  export let maximize = true;
  export let disabled = false;
  export let size = 12;
  export let gap = 8;
  export let onClose: (() => void) | undefined = undefined;
  export let onMinimize: (() => void) | undefined = undefined;
  export let onMaximize: (() => void) | undefined = undefined;

  let closeState: IconState = "default";
  let minimizeState: IconState = "default";
  let maximizeState: IconState = "default";

  const buttonStyle = () => {
    const opacity = disabled ? 0.45 : 1;
    const cursor = disabled ? "default" : "pointer";
    return `border:none;padding:0;background:transparent;cursor:${cursor};display:inline-flex;align-items:center;justify-content:center;opacity:${opacity}`;
  };

  const containerStyle = () => `display:flex;align-items:center;gap:${gap}px`;

  const setState = (kind: "close" | "minimize" | "maximize", next: IconState) => {
    if (kind === "close") closeState = next;
    if (kind === "minimize") minimizeState = next;
    if (kind === "maximize") maximizeState = next;
  };

  const getState = (kind: "close" | "minimize" | "maximize") => {
    if (kind === "close") return closeState;
    if (kind === "minimize") return minimizeState;
    return maximizeState;
  };

  const onEnter = (kind: "close" | "minimize" | "maximize") => {
    if (!disabled) setState(kind, "hover");
  };
  const onLeave = (kind: "close" | "minimize" | "maximize") => {
    if (!disabled) setState(kind, "default");
  };
  const onDown = (kind: "close" | "minimize" | "maximize") => {
    if (!disabled) setState(kind, "active");
  };
  const onUp = (kind: "close" | "minimize" | "maximize") => {
    if (!disabled) setState(kind, "hover");
  };
  const onBlur = (kind: "close" | "minimize" | "maximize") => {
    if (!disabled) setState(kind, "default");
  };
</script>

<div class="mac-traffic-light" style={containerStyle()}>
  {#if close}
    <button
      type="button"
      class="mac-btn mac-btn--close"
      style={buttonStyle()}
      disabled={disabled}
      aria-disabled={disabled ? "true" : undefined}
      on:click={() => {
        if (!disabled) onClose?.();
      }}
      on:mouseenter={() => onEnter("close")}
      on:mouseleave={() => onLeave("close")}
      on:mousedown={() => onDown("close")}
      on:mouseup={() => onUp("close")}
      on:blur={() => onBlur("close")}
    >
      <CloseIcon state={disabled ? "default" : getState("close")} width={size} height={size} />
    </button>
  {/if}

  {#if minimize}
    <button
      type="button"
      class="mac-btn mac-btn--minimize"
      style={buttonStyle()}
      disabled={disabled}
      aria-disabled={disabled ? "true" : undefined}
      on:click={() => {
        if (!disabled) onMinimize?.();
      }}
      on:mouseenter={() => onEnter("minimize")}
      on:mouseleave={() => onLeave("minimize")}
      on:mousedown={() => onDown("minimize")}
      on:mouseup={() => onUp("minimize")}
      on:blur={() => onBlur("minimize")}
    >
      <MinimizeIcon state={disabled ? "default" : getState("minimize")} width={size} height={size} />
    </button>
  {/if}

  {#if maximize}
    <button
      type="button"
      class="mac-btn mac-btn--maximize"
      style={buttonStyle()}
      disabled={disabled}
      aria-disabled={disabled ? "true" : undefined}
      on:click={() => {
        if (!disabled) onMaximize?.();
      }}
      on:mouseenter={() => onEnter("maximize")}
      on:mouseleave={() => onLeave("maximize")}
      on:mousedown={() => onDown("maximize")}
      on:mouseup={() => onUp("maximize")}
      on:blur={() => onBlur("maximize")}
    >
      <MaximizeIcon state={disabled ? "default" : getState("maximize")} width={size} height={size} />
    </button>
  {/if}
</div>
